hmrc/third-party-developer-frontend

app/views/include/passwords.scala.html

APIS-3499 Removed aria-labelled-by attributes, which duplicate the for attribute functionality.

---

app/connectors/ThirdPartyApplicationConnector.scala

When getting applications by a single collaborator (email)

APIS-4406 - Added logging around problem call to TPA

---

conf/application.conf

- Some AT's were failing without this.

APIS-4377 - Added https://www.googletagmanager.com to img-src CSP

---

app/config/ApplicationConfig.scala
app/connectors/ApiSubscriptionFieldsConnector.scala
app/connectors/ProxiedHttpClient.scala
app/connectors/ThirdPartyApplicationConnector.scala
test/unit/connectors/ApiSubscriptionFieldsBaseConnectorSpec.scala
test/unit/connectors/ApiSubscriptionFieldsConnectorsSpec.scala
test/unit/connectors/ProxiedHttpClientSpec.scala

APIS-4442 - Add authentication token x-api-key

---

app/controllers/UserLoginAccount.scala
app/service/MfaMandateService.scala
test/it/LoginCSRFIntegrationSpec.scala
test/unit/controllers/UserLoginAccountSpec.scala
test/unit/service/MfaMandateServiceSpec.scala

- And if the Admin user is for a Principal (Production) app.

APIS-4501 - Only displays the MFA mandate warning for admin users

---

app/controllers/UserLoginAccount.scala
app/controllers/UserLogoutAccount.scala
test/unit/controllers/UserLoginAccountSpec.scala
test/unit/controllers/UserLogoutAccountSpec.scala

- Tidied up some controller code
- Fixed a problem with implicits which upset intellij

APIS-4501 - Refactored some controller code

---

app/domain/BackButton.scala
app/domain/NavLink.scala
app/views/include/devMain.scala.html
app/views/include/main.scala.html
app/views/logInAccessCode.scala.html
app/views/protectaccount/protectAccount.scala.html
app/views/protectaccount/protectAccountAccessCode.scala.html
app/views/protectaccount/protectAccountNoAccessCode.scala.html
app/views/protectaccount/protectAccountNoAccessCodeComplete.scala.html
app/views/protectaccount/protectAccountRemovalAccessCode.scala.html
app/views/protectaccount/protectAccountRemovalComplete.scala.html
app/views/protectaccount/protectAccountRemovalConfirmation.scala.html
app/views/protectaccount/protectAccountSetup.scala.html
app/views/protectaccount/protectedAccount.scala.html
app/views/signIn.scala.html
build.sbt
test/component/pages/pages.scala
test/component/steps/Env.scala
test/component/steps/LoginSteps.scala
test/unit/controllers/UserLoginAccountSpec.scala

- Updated text content
- Removed some breadcrumbs and replaced with 'back' buttons
- Removed some left nav

APIS-4496 - Changed some journeys to match UX

---

app/controllers/ProtectAccount.scala
app/controllers/UserLoginAccount.scala
app/views/add2SV.scala.html
app/views/userDidNotAdd2SV.scala.html
conf/app.routes
test/it/LoginCSRFIntegrationSpec.scala
test/unit/controllers/ProtectAccountSpec.scala
test/unit/controllers/UserLoginAccountSpec.scala
test/unit/views/Add2SVSpec.scala

- Fixed some UX re back button, profile name & breadcrumbs

APIS-4496 - Fixed login to do a redirect

---

app/controllers/Subscriptions.scala
app/service/ApplicationService.scala
conf/app.routes

- This was added as part of diagnosing a HTTP connect problem and can
now be removed.

BDOG-381 - Removed some test / diagnostic code

---

app/controllers/Support.scala
test/unit/controllers/SupportSpec.scala

- Doesn't pre fill your name + email
- Shows the register / sign-out links at the top

APIS-4496 - Fixed the support page when part logged in

---

app/config/ErrorHandler.scala
app/domain/Application.scala
app/domain/Session.scala
run_all_tests_no_coverage.sh

APIS-4496 - Fixed error for missing application ids

---

app/controllers/ApplicationCheck.scala
app/controllers/ManageApplications.scala

- In both pages with validation errors it didn't display the error message anchor link  correctly.

APIS-4386 - Fixed bug in app name validation

---

app/views/addApplicationPrincipalSuccess.scala.html
app/views/addApplicationSubordinateSuccess.scala.html

- On new sandbox / prod success pages.

APIS-4536 - Changed breadcrumbs and page titles

---

app/views/addApplicationSubordinateEmptyNest.scala.html
test/unit/views/ViewAllApplicationsPageSpec.scala

- Now skips the start of the sandbox journey warning (as the empty nest page already does this)

APIS-4531 - Fix the empty nest sandbox journey.

---

app/controllers/AddApplication.scala
app/controllers/UIModel.scala
app/views/addApplicationStartPrincipal.scala.html
app/views/addApplicationStartSubordinate.scala.html
app/views/include/leftHandNav.scala.html
app/views/manageApplications.scala.html
conf/app.routes
test/unit/controllers/AddApplicationStartSpec.scala
test/unit/controllers/ApplicationSummaryTest.scala
test/unit/views/ViewAllApplicationsPageSpec.scala
test/utils/ViewHelpers.scala

- Changed menu to 'Get production credentials'
- Fixed wording
- Added a 'Get production credentials' green button if no production apps.
- Added new sandbox journey start page.

APIS-4581 - View all and request prod creds

---

app/assets/stylesheets/ad-hoc.scss
app/views/manageApplications.scala.html
app/views/tenDaysWarning.scala.html

- Fixed missing comma
- Made interrupt page line break at half its width
- Fixed some whitespace on the applications list page

APIS-4601 - UI tweaks

---

app/views/applicationcheck/apiSubscriptions.scala.html
test/unit/controllers/ApplicationCheckSpec.scala

- Changed title
- Removed breadcrumbs and added back button
- Tweaked submit button title

APIS-4617 - Change the application check subscription page

---

app/controllers/Subscriptions.scala
app/controllers/UIModel.scala
test/unit/controllers/SubscriptionsSpec.scala
test/unit/views/SubscriptionsSpec.scala

Removed loading of credentials when loading the subs page
- It wasn't being used anywhere in the code or the views.

APIS-4483 Removed loading of credentials when loading the subs page

---

app/connectors/ApiSubscriptionFieldsConnector.scala
app/connectors/CustomResponseHandlers.scala
app/controllers/ManageSubscriptions.scala
app/domain/ApiSubscriptionFields.scala
app/service/SubscriptionFieldsService.scala
app/views/addApplicationName.scala.html
app/views/managesubscriptions/editApiMetadata.scala.html
app/views/managesubscriptions/listApiSubscriptions.scala.html
conf/app.routes
scalastyle-config.xml
test/connectors/SubscriptionFieldsConnectorSpec.scala
test/controllers/ManageSubscriptionsSpec.scala
test/service/ApplicationServiceSpec.scala
test/service/SubscriptionFieldsServiceSpec.scala

Add api-subscription-fields validation to TPDFE

APIS-4730 - api-subscription-fields validation in FE

---

app/service/ApplicationService.scala
test/service/ApplicationServiceSpec.scala

Don't swallow unexpected errors / responses from the backend.
Co-authored-by: Anjum Abbas <khaakpaayali@gmail.com>

APIS-4784 - Error when failing to save subscription field values

---

app/views/partials/termsOfUse.scala.html

Fix email address

---

app/views/createJourney/SubscriptionConfigurationPageView.scala.html
app/views/managesubscriptions/EditApiMetadataView.scala.html

Co-authored-by: Andy Spaven <andyspav@gmail.com>

APIS-4855 - Fixing ApiVersion toString problem

---

app/config/ApplicationConfig.scala
app/views/include/Main.scala.html
test/views/MainTemplateSpec.scala

A#PIS-4889 - Added userAction param to accessibility statement link - With details of the current url path

APIS-4888 - Added footer link to accessibility statement.

---

test/controllers/DeletePrincipalApplicationSpec.scala
test/controllers/DetailsSpec.scala
test/controllers/ManageSubscriptionsSpec.scala
test/controllers/PushPullNotificationsSpec.scala

- As the former creates a new (orphaned) fake application

Replaced called to fakeApplicaiton() to app

---

app/views/emailpreferences/EmailPreferencesSummaryView.scala.html
test/views/emailpreferences/EmailPreferencesSummaryViewSpec.scala

Co-authored-by: Chris Rowe <chris@chrisrowe.co.uk>

API-4441: Email preferences, edit topics from email preferences summary page

---

app/connectors/ThirdPartyApplicationConnector.scala
app/controllers/Subscriptions.scala
app/domain/models/apidefinitions/ApiDefinition.scala
app/domain/models/applications/Application.scala
app/domain/models/subscriptions/APISubscription.scala
app/domain/models/subscriptions/Fields.scala
app/domain/services/SubscriptionsJsonFormatters.scala
app/service/ApplicationService.scala
component/stubs/Stubs.scala
it/connectors/stubs/Stubs.scala
test/builder/ApplicationBuilder.scala
test/builder/SubscriptionsBuilder.scala
test/connectors/ProxiedHttpClientSpec.scala
test/connectors/ThirdPartyApplicationConnectorSpec.scala
test/controllers/ApplicationCheckSpec.scala
test/controllers/CheckYourAnswersSpec.scala
test/controllers/DeletePrincipalApplicationSpec.scala
test/controllers/ManageTeamSpec.scala
test/controllers/SubscriptionsSpec.scala
test/controllers/TermsOfUseSpec.scala
test/mocks/service/ApplicationServiceMock.scala
test/service/ApplicationServiceSpec.scala

Co-authored-by: Pete Slater <pslater@equalexperts.com>
Co-authored-by: Anjum Abbas <khaakpaayali@gmail.com>

APIS-4836 - Remove call to subs in TPA, replace with APM

---

app/connectors/ApmConnector.scala
app/connectors/ThirdPartyApplicationConnector.scala
app/controllers/Subscriptions.scala
app/service/ApplicationService.scala
app/service/SubscriptionsService.scala
test/connectors/ApmConnectorSpec.scala
test/connectors/ProxiedHttpClientSpec.scala
test/connectors/ThirdPartyApplicationConnectorSpec.scala
test/controllers/SubscriptionsSpec.scala
test/mocks/service/ApplicationServiceMock.scala
test/service/ApplicationServiceSpec.scala
test/service/SubscriptionsServiceSpec.scala

Co-authored-by: Pete Slater <pslater@equalexperts.com>

APIS-4836 - TPDFE using APM for subscribing

---

app/config/ApplicationConfig.scala
app/views/ForgotPasswordView.scala.html
app/views/ResendConfirmationView.scala.html
app/views/SignInView.scala.html
app/views/include/passwords2.scala.html
app/views/templates/govUkWrapper.scala.html
conf/application.conf

- Add report a problem base URL to config + govUkWrapper
- `Is this page working properly` link now opens in the same tab rather than in a new one.

Phase-one-design-fixes

---

app/views/templates/FooterConfig.scala
app/views/templates/FooterLinks.scala
app/views/templates/govUkWrapper.scala.html

- Refactor accessibility link 
- Refactor report problem link
- Rename appConfig to footerConfig

Phase-one-design-fix: Refactor accessibility link + report problem link

---

app/views/include/DevMain2.scala.html
app/views/include/Main.scala.html
app/views/templates/govUkWrapper.scala.html

- Implement HMRC tracking consent snippet for upgraded & non-upgraded templates

APIS-5345: Cookie banner now appearing on Developer Hub

---

app/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/models/views/FeedbackBanner.scala
app/views/include/DevMain2.scala.html
app/views/include/FeedbackBannerView.scala.html
app/views/ipAllowlist/AddCidrBlockView.scala.html
app/views/ipAllowlist/AllowedIpsView.scala.html
app/views/ipAllowlist/ChangeIpAllowlistSuccessView.scala.html
app/views/ipAllowlist/EditIpAllowlistView.scala.html
app/views/ipAllowlist/IpAllowlistView.scala.html
app/views/ipAllowlist/RemoveCidrBlockView.scala.html
app/views/ipAllowlist/RemoveIpAllowlistSuccessView.scala.html
app/views/ipAllowlist/RemoveIpAllowlistView.scala.html
app/views/ipAllowlist/ReviewIpAllowlistView.scala.html
app/views/ipAllowlist/SettingUpAllowlistView.scala.html
app/views/ipAllowlist/StartIpAllowlistView.scala.html
conf/application.conf
test/views/ForgotPasswordViewSpec.scala
test/views/MainTemplateSpec.scala
test/views/include/FeedbackBannerViewSpec.scala

Co-authored-by: Matthew Clark <36630558+mattclark-zerogravit@users.noreply.github.com>
o

API-5295: Added feedback tool

---

app/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/Details.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/forms.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/models/applications/Application.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/models/connectors/DeskproTicket.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationService.scala
app/views/ChangeOfApplicationNameConfirmationView.scala.html
app/views/DetailsView.scala.html
app/views/RequestChangeOfApplicationNameView.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/DetailsSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationServiceSpec.scala

This PR is for both APIS-5813 (Create Deskpro ticket for SDST when Dev hub user has requested application name change) and APIS-5744 (Allow dev hub user to initiate "change of application name")

APIS-5813 Add ability for DevHub user to request change to production app name

---

app/views/managesubscriptions/ListApiSubscriptionsView.scala.html

APID-554 Improve subscription config table mark-up for accessibility

---

app/uk/gov/hmrc/apiplatform/modules/applications/services/CollaboratorService.scala
app/uk/gov/hmrc/apiplatform/modules/submissions/controllers/CancelRequestController.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/connectors/ApplicationCommandConnector.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/Credentials.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/models/controllers/Crumb.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationService.scala
app/uk/gov/hmrc/thirdpartydeveloperfrontend/service/SubscriptionsService.scala
app/views/ipAllowlist/ChangeIpAllowlistSuccessView.scala.html
app/views/ipAllowlist/EditIpAllowlistView.scala.html
app/views/ipAllowlist/RemoveIpAllowlistSuccessView.scala.html
app/views/ipAllowlist/RemoveIpAllowlistView.scala.html
app/views/ipAllowlist/ReviewIpAllowlistView.scala.html
app/views/ipAllowlist/StartIpAllowlistView.scala.html
app/views/managesubscriptions/EditApiMetadataFieldView.scala.html
app/views/managesubscriptions/EditApiMetadataView.scala.html
test/uk/gov/hmrc/apiplatform/modules/submissions/controllers/CancelRequestControllerSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/connectors/ApplicationCommandConnectorSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/endpointauth/EndpointScenarioSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/controllers/endpointauth/MockConnectors.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/mocks/connectors/ApplicationCommandConnectorMockModule.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationServiceSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationServiceTeamMembersSpec.scala
test/uk/gov/hmrc/thirdpartydeveloperfrontend/service/ApplicationServiceUpliftSpec.scala

API-6929 - Update breacrumbs for Configure Metadata

---

app/views/checkpages/ContactDetailsView.scala.html

Fix issue where 'Use my details' checkbox doesn't work due to CSP changes.

APSR-1717 Fix issue in contact details page

---

app/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/models/views/NavLink.scala
app/views/templates/govUkWrapper.scala.html
test/uk/gov/hmrc/thirdpartydeveloperfrontend/domain/NavLinkSpec.scala

Reverts hmrc/third-party-developer-frontend#856

Revert "APIS-7317 Move service availability link from header to footer"
